import Head from 'next/head'
import { Inter } from '@next/font/google'
import {getFeaturedProducts, getProducts} from "@/utils/wooCommerceApi";
import Link from "next/link";
import {useDispatch, useSelector} from "react-redux";
import {addToCart} from "@/store/cartSlice";

const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
    const {products} = props;
    const selector = useSelector(state => state.cart.in);
    const dispatch = useDispatch();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          {/* boostrap hero banner */}
          <div className="container-fluid" style={{
              backgroundImage:'url(/laptop_12.jpg)',
                backgroundSize: 'cover',
                backgroundPosition: 'center',
                backgroundRepeat: 'no-repeat',
                height: '500px',
                width: '100%',
          }}>
            <div className="container h-100">
                <div className="row h-100 justify-content-start align-items-center">
                    <div className="col-6">
                        <h1>Hero Banner</h1>
                        <button className={"btn btn-danger px-3"}>Shop Now</button>
                    </div>
                </div>
            </div>
          </div>
            <div className="container mt-5">
                <div className="row">
                    <div className="col-12">
                        <h1>Featured Product</h1>
                        <hr/>
                        <div className="row">
                            { products.map( product => (
                                <div className="col-12 col-md-4">
                                    <div className="card mb-3 mb-md-0">
                                        <img style={{maxHeight:'300px',objectFit:"cover"}} src={product.images[0].src} className="card-img-top" alt="..."/>
                                        <div className="card-body">
                                            <h5 className="card-title">{product.name}</h5>
                                            <Link
                                                href={`shop/${product.slug}/`}
                                            >
                                                <div className="btn btn-primary">voir le produit</div>
                                            </Link>
                                            <div className="btn btn-danger ms-1" onClick={() => {
                                                dispatch(addToCart({
                                                    id: product.id,
                                                    name: product.name,
                                                    price: product.price,
                                                    image: product.images[0].src,
                                                    quantity: 1,
                                                }))
                                                console.log(selector)
                                            }}><i className="fa-solid fa-circle-plus"></i></div>
                                        </div>
                                    </div>
                                </div>
                                ))
                            }
                        </div>
                    </div>
                </div>
            </div>
      </main>
    </>
  )
}

// get product
export async function getStaticProps() {
    const products = await getFeaturedProducts().catch((err) => {
        console.log(err)
    } )

    if(!products) {
        return {
            notFound: true,
        }
    }

    return {
        props: {
            products: products.data,
        },
    }
}
